export const USER_LOGIN_REQUEST = "USER_LOGIN_REQUEST";
export const USER_LOGIN_SUCCESS = "USER_LOGIN_SUCCESS";
export const USER_LOGIN_FAIL = "USER_LOGIN_FAIL";
export const MESSAGES_TEMPS_REEL = "MESSAGES_TEMPS_REEL";
export const USER_LOGOUT = "USER_LOGOUT";
